version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'

  - package-ecosystem: 'npm'
    directory: '/packages/dx-chart-core/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-core/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-demo-shell/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-grid-core/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-bootstrap4/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-chart/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-chart-bootstrap4/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-chart-demos/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-chart-material-ui/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-common/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-core/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-grid/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-grid-bootstrap3/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-grid-bootstrap4/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-grid-demos/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-grid-export/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-grid-material-ui/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-scheduler/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-scheduler-demos/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-react-scheduler-material-ui/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-scheduler-core/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-site/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-styles/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-testing/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-vue-core/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-vue-grid/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-vue-grid-bootstrap4/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/packages/dx-vue-grid-demos/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'DevExpress/devextreme-devops'
    open-pull-requests-limit: 0
