titleOnly: true

scopes:
  - chart-core
  - core
  - demo-shell
  - grid-core
  - react-bootstrap4
  - react-chart
  - react-chart-bootstrap4
  - react-chart-demos
  - react-chart-material-ui
  - react-common
  - react-core
  - react-grid
  - react-grid-bootstrap3
  - react-grid-bootstrap4
  - react-grid-demos
  - react-grid-material-ui
  - react-scheduler
  - react-scheduler-demos
  - react-scheduler-material-ui
  - scheduler-core
  - styles
  - testing
