export default () => {
    return (
      <div>
        <DataGrid
          dataSource={rows}
        >
          <Column
            dataField={'region'}
            caption={'Region'}
            groupIndex={0}
          />
          <Column
            dataField={'customer'}
            caption={'Customer'}
          />
          <Column
            dataField={'product'}
            caption={'Product'}
          />
          <Column
            dataField={'units'}
            caption={'Units'}
          />
          <Column
            dataField={'amount'}
            caption={'Sale Amount'}
            alignment={'right'}
            format="currency"
          />
          <Summary>
            <GroupItem
              column="amount"
              summaryType="sum"
              valueFormat="currency"
            />
            <GroupItem
              column="units"
              summaryType="sum"
              alignByColumn={true}
            />
            <GroupItem
              column="amount"
              summaryType="max"
              valueFormat="currency"
              alignByColumn={true}
            />
            <GroupItem
              column="region"
              summaryType="count"
              showInGroupFooter={true}
            />
            <GroupItem
              column="amount"
              summaryType="sum"
              valueFormat="currency"
              showInGroupFooter={true}
            />
          </Summary>
        </DataGrid>
      </div>
    );
};