export default () => {
    return (
      <div>
        <DataGrid
          dataSource={rows}
        >
          <Editing
            allowUpdating={true}
            allowAdding={true}
            allowDeleting={true}
            mode="row"
          />
          <Column
            dataField={'name'}
            caption={'Name'}
          />
          <Column
            dataField={'gender'}
            caption={'Gender'}
          />
          <Column
            dataField={'city'}
            caption={'City'}
          />
          <Column
            dataField={'car'}
            caption={'Car'}
          />
        </DataGrid>
      </div>
    );
};